FROM python:3-alpine as builder

ENV PATH="/opt/.env/bin:${PATH}"

COPY ./ /unit-test

RUN \
  apk update && \
  apk add build-base && \
  python -m venv /opt/.env && \
  pip install --upgrade pip && \
  pip install -r /unit-test/unit-test/requirements.txt

FROM python:3-alpine

ARG UID=1005
ARG USERNAME=flask

COPY --from=builder /opt/.env /opt/.env
COPY --from=builder /unit-test /unit-test

ENV PATH="/opt/.env/bin:${PATH}"

RUN \
  apk update && \
  adduser -g ${USERNAME} ${USERNAME} --disabled-password --uid ${UID} && \
  chown -R ${USERNAME} /unit-test

WORKDIR /unit-test/unit-test

USER ${USERNAME}

 

ENTRYPOINT ["python", "main.py"]