FROM python:3-alpine as builder

ENV PATH="/opt/.env/bin:${PATH}"

COPY ./ /task

RUN \
  apk update && \
  apk add build-base && \
  python -m venv /opt/.env && \
  pip install --upgrade pip && \
  pip install -r /task/task/requirements.txt

FROM python:3-alpine

ARG UID=1005
ARG USERNAME=flask

COPY --from=builder /opt/.env /opt/.env
COPY --from=builder /task /task

ENV PATH="/opt/.env/bin:${PATH}"

RUN \
  apk update && \
  adduser -g ${USERNAME} ${USERNAME} --disabled-password --uid ${UID} && \
  chown -R ${USERNAME} /task

WORKDIR /task/task

USER ${USERNAME}

 

ENTRYPOINT ["python", "solution.py"]